config/routes.rb
Rails.application.routes.draw do
  
  devise_for :students
  devise_for :teachers
  devise_for :admins
  
  namespace :admin do
    root 'dashboard#index'
    resources :students do
      collection do
        get :search
      end
    end
    resources :teachers do
      collection do
        get :search
      end
    end
    resources :courses do
      collection do
        get :search
      end
    end
    resources :sections
    resources :enrollments
    resources :dashboard
  end

  namespace :student do
    root 'dashboard#index'
    resources :dashboard
    get 'dashboard/enrollments/:id', to: 'dashboard#enrollments', as: :enrollments
    get 'dashboard/student_history/:id', to: 'dashboard#student_history', as: :history
  end

  namespace :teacher do
    root 'dashboard#index'
    resources :dashboard
    get 'dashboard/section/:id', to: 'dashboard#section', as: :sections
    get 'dashboard/course/:id', to: 'dashboard#course', as: :courses
  end

  # Defines the root path route ("/")
  get 'home/index'
  root "home#index"
  get 'download_file', to: 'downloads#download_file'
  default_url_options :host => "localhost:3000"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :sections
    has_and_belongs_to_many :teachers , join_table: "expertises"

    validates :course_title, presence: true
    validates :course_code, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :section
  belongs_to :student
  belongs_to :semester
  belongs_to :grade
end

app/models/grade.rb
class Grade < ApplicationRecord
    has_many :enrollments
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :enrollments
    belongs_to :teacher
    belongs_to :semester
    belongs_to :course

    validates :section_name, presence: true
end

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :student_semesters
    has_many :students, :through => :student_semesters
    has_many :sections
    has_many :enrollments
end

app/models/student.rb
class Student < ApplicationRecord
  attr_accessor :enroll_year, :semester_no, :semester_type
  after_create :semester_enrollment
  after_update :semester_enrollment
  has_many :student_semesters
  has_many :semesters, :through => :student_semesters
  has_many :enrollments
  has_one_attached :image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   PASSWORD_FORMAT = /\A(?=.{8,})(?=.*[A-Z])(?=.*[[:^alnum:]])/x.freeze

  validates :password, presence: true,
      format: { with: PASSWORD_FORMAT}, confirmation: true,
      format: { with: PASSWORD_FORMAT}

  validates :first_name, :last_name, :Date_of_Birth, :roll_no, presence: true

  private
   def semester_enrollment
    semester = Semester.where(semester_type: self.semester_type, semester_no: self.semester_no).ids[0]
    if self.semester[-1].id = semester_id
      return
    else
     self.student_semesters.create(semester_id: semester, enroll_year: self.enroll_year)
    end
   end
end

app/models/student_semester.rb
class StudentSemester < ApplicationRecord
    belongs_to :student
    belongs_to :semester
end

app/models/teacher.rb
class Teacher < ApplicationRecord

  has_many :sections
  has_and_belongs_to_many :courses, join_table: "expertises"
  has_one_attached :image, dependent: :destroy 
#   validates :photos, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..(5.megabytes) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_FORMAT = /\A(?=.{8,})(?=.*[A-Z])(?=.*[[:^alnum:]])/x.freeze

         validates :password, presence: true,
         format: { with: PASSWORD_FORMAT}, confirmation: true,
         format: { with: PASSWORD_FORMAT}
   
     validates :first_name, :last_name, :Date_of_Birth, presence: true
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminAuthenticateController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
    def download_file

        redirect_to root_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def contact 
  end
  def about
  end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < Student::StudentAuthenticateController
    before_action :authenticate_student!
    def index
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        @student.semester_type = params[:semester_type]
        @student.semester_no = params[:semester_no]
        @student.enroll_year = params[:enroll_year]
        if @student.update(profile_params)
            sign_in @student, bypass: true
            redirect_to student_dashboard_index_path
        else
            flash[:notice] = "You can not update"
            render :edit
        end
    end
    
    def enrollments
        @enrollments = current_student.semesters[-1].enrollments.where(grade_id:1, student_id: current_student.id)
    end

    def student_history
        @semesters = current_student.semesters
    end

    private
     
    def profile_params
        params.require(:student).permit(:first_name, :last_name, :Date_of_Birth, :email, :password, :image)
    end
end

app/controllers/teacher/dashboard_controller.rb
class Teacher::DashboardController < Teacher::TeacherAuthenticateController
   
    def index;
    end

    def show;
     @teacher = Teacher.find(params[:id])
    end

    def edit
      @teacher = Teacher.find(params[:id])
    end

    def update
      @teacher = Teacher.find(params[:id])
      if @teacher.update(teacher_profile)
          sign_in @teacher, bypass: true
        redirect_to teacher_dashboard_index_path
      else
        flash[:notice] = "You can not update, Try late"
        render edit
      end
    end

    def course
        @courses = current_teacher.sections
    end

    def section
        @sections = current_teacher.sections
    end
  
    private 
    
    def teacher_profile
      params.require(:teacher).permit(:first_name, :last_name, :Date_of_Birth, :email, :password, :image)
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin_session_helper.rb
module AdminSessionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student/dashboard_helper.rb
module Student::DashboardHelper
end

app/helpers/student_registration_helper.rb
module StudentRegistrationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher/dashboard_helper.rb
module Teacher::DashboardHelper
end

app/views/admin/dashboard/_cards.html.erb
<div class="row dashboard_cards">
	<div class="col-md-4 d-flex justify-content-center" >
		<div class="card text-center shadow mt-3 p-2 " id="card1" style="width:400px">
			<div class="card-body" >
				<h5 class="card-title">Teachers</h5>
				<p class="card-text">We are warmly welcome to you at our Learning Management System, The total number of Teachers on our LMS are <%= Teacher.count %>.</p>
				<%= link_to "Add more", new_admin_teacher_path, class:"btn btn-info"%>
			</div>
		</div>
	</div>
	<div class="col-md-4 d-flex justify-content-center">
		<div class="card text-center shadow mt-3 p-2 " id="card1" style="width:400px">
			<div class="card-body">
				<h5 class="card-title">Students</h5>
				<p class="card-text">We are warmly welcome to you at our Learning Management System, The total number of Students on our LMS are <%= Student.count %>.</p>
				<%= link_to "Add more", new_admin_student_path, class:"btn btn-info"%>
			</div>
		</div>
	</div>
	<div class="col-md-4 d-flex justify-content-center">
		<div class="card text-center shadow mt-3 p-2 " id="card1" style="width:400px">
			<div class="card-body" >
				<h5 class="card-title">Enrollments</h5>
				<p class="card-text">We are warmly welcome to you at our Learning Management System, The total number of Enrollments on our LMS are <%= Enrollment.count %>.</p>
				<%= link_to "Add more", new_admin_enrollment_path, class:"btn btn-info"%>
			</div>
		</div>
	</div>
</div>

<div class="row dashboard_cards1">
	<div class= "col-md-6 d-flex justify-content-center">
		<div class="card text-center shadow mt-3 p-2 " id="card1" style="width:400px">
			<div class="card-body" >
				<h5 class="card-title">Sections</h5>
				<p class="card-text">We are warmly welcome to you at our Learning Management System, The total number of Sections on our LMS are <%= Section.count %>.</p>
				<%= link_to "Add more", new_admin_section_path, class:"btn btn-info"%>
			</div>
		</div>
	</div>
	<div class= "col-md-6 d-flex justify-content-center">
		<div class="card text-center shadow mt-3 p-2 " id="card1" style="width:400px">
			<div class="card-body" >
				<h5 class="card-title">Courses</h5>
				<p class="card-text">We are warmly welcome to you at our Learning Management System, The total number of Courses on our LMS are <%= Course.count %>.</p>
				<%= link_to "Add more", new_admin_course_path, class:"btn btn-info"%>
			</div>
		</div>   
	</div>
</div>

app/views/admin/dashboard/_carousel.html.erb
<div class="container my-5">
	<div class="ombre-externe">
		<div class="ombre-interne">
				<div id="carouselExampleCaptions" class="carousel slide " data-bs-ride="carousel">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<img src="https://nsm09.casimages.com/img/2021/07/21//21072103063525998217500508.jpg" class="d-block w-100 peinture-ombre-interne-fine" alt="...">
							<div class="carousel-caption">
								<h5>
									LMS
								</h5>
								<p>
								</p>
							</div>
						</div>
						<div class="carousel-item">
							<img src="https://nsm09.casimages.com/img/2021/07/21//21072103063625998217500510.jpg" class="d-block w-100" alt="...">
							<div class="carousel-caption">
								<h5>
									Manage Teachers
								</h5>
								<p>
								</p>
							</div>
						</div>
						<div class="carousel-item">
							<img src="https://nsm09.casimages.com/img/2021/07/21//21072103063625998217500509.jpg" class="d-block w-100" alt="...">
							<div class="carousel-caption">
								<h5>
									Manage Students 
								</h5>
								<p> 
								</p>
							</div>
						</div>
					</div>
					<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</button>
					<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</button>
				</div>
		</div>
		<!-- ombre-interne -->
	</div>
	<!-- ombre-externe -->
</div>

app/views/admin/dashboard/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" >Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <a class="nav-link" href="/admin/teachers?format=turbo_stream">Teacher</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/admin/students?format=turbo_stream">Student</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="/admin/courses?format=turbo_stream">Courses</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="/admin/enrollments?format=turbo_stream">Enrollment</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="/admin/sections?format=turbo_stream">Section</a>
        </li>
        <li class="nav-item">
            <%= link_to "Log out", destroy_admin_session_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/dashboard/index.html.erb
<%=  turbo_frame_tag 'main' do%>
<%= render "carousel" %>
<div>
    <p>
        <%= render "cards" %>
    </p>
</div>
<% end %>