config/routes.rb
Rails.application.routes.draw do
  
  devise_for :students
  devise_for :teachers
  devise_for :admins
  
  namespace :admin do
    root 'dashboard#index'
    resources :students do
      collection do
        get :search
      end
    end
    resources :teachers do
      collection do
        get :search
      end
    end
    resources :courses do
      collection do
        get :search
      end
    end
    resources :sections
    resources :enrollments
    resources :dashboard
  end

  namespace :student do
    root 'dashboard#index'
    resources :dashboard
    get 'dashboard/enrollments/:id', to: 'dashboard#enrollments', as: :enrollments
    get 'dashboard/student_history/:id', to: 'dashboard#student_history', as: :history
  end

  namespace :teacher do
    root 'dashboard#index'
    resources :dashboard
    get 'dashboard/section/:id', to: 'dashboard#section', as: :sections
    get 'dashboard/course/:id', to: 'dashboard#course', as: :courses
  end

  # Defines the root path route ("/")
  get 'home/index'
  root "home#index"
  get 'download_file', to: 'downloads#download_file'
  default_url_options :host => "localhost:3000"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :sections
    has_and_belongs_to_many :teachers , join_table: "expertises"

    validates :course_title, presence: true
    validates :course_code, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :section
  belongs_to :student
  belongs_to :semester
  belongs_to :grade
end

app/models/grade.rb
class Grade < ApplicationRecord
    has_many :enrollments
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :enrollments
    belongs_to :teacher
    belongs_to :semester
    belongs_to :course

    validates :section_name, presence: true
end

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :student_semesters
    has_many :students, :through => :student_semesters
    has_many :sections
    has_many :enrollments
end

app/models/student.rb
class Student < ApplicationRecord
  attr_accessor :enroll_year, :semester_no, :semester_type
  after_create :semester_enrollment
  after_update :semester_enrollment
  has_many :student_semesters
  has_many :semesters, :through => :student_semesters
  has_many :enrollments
  has_one_attached :image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   PASSWORD_FORMAT = /\A(?=.{8,})(?=.*[A-Z])(?=.*[[:^alnum:]])/x.freeze

  validates :password, presence: true,
      format: { with: PASSWORD_FORMAT}, confirmation: true,
      format: { with: PASSWORD_FORMAT}

  validates :first_name, :last_name, :Date_of_Birth, :roll_no, presence: true

  private
   def semester_enrollment
    semester = Semester.where(semester_type: self.semester_type, semester_no: self.semester_no).ids[0]
    if self.semester[-1].id = semester_id
      return
    else
     self.student_semesters.create(semester_id: semester, enroll_year: self.enroll_year)
    end
   end
end

app/models/student_semester.rb
class StudentSemester < ApplicationRecord
    belongs_to :student
    belongs_to :semester
end

app/models/teacher.rb
class Teacher < ApplicationRecord

  has_many :sections
  has_and_belongs_to_many :courses, join_table: "expertises"
  has_one_attached :image, dependent: :destroy 
#   validates :photos, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..(5.megabytes) }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_FORMAT = /\A(?=.{8,})(?=.*[A-Z])(?=.*[[:^alnum:]])/x.freeze

         validates :password, presence: true,
         format: { with: PASSWORD_FORMAT}, confirmation: true,
         format: { with: PASSWORD_FORMAT}
   
     validates :first_name, :last_name, :Date_of_Birth, presence: true
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::AdminAuthenticateController
	before_action :find_section, only: %i[update destroy edit] 
	def index
		@sections = Section.all
		respond_to do |format|
			format.turbo_stream{
			  render turbo_stream: turbo_stream.update('main', template: 'admin/sections/index')
			}
		  end
	end
	
	def new
		@section = Section.new
	end

	def create
		@section = Section.new(section_params)
		if @section.save
			redirect_to admin_sections_path
			flash[:notice] = "A new Section is added"
		else
			render :new, status: :unprocessable_entity
			flash[:alert] = "sorry, unable to add section"
		end
	end

	def edit
		
	end

	def update
		if @section.update(section_params)
			redirect_to admin_sections_path
			flash[:notice] = "Section is updated"
		else
			render :edit, status: :unprocessable_entity
			flash[:alert] = "Can't update this section"
		end
	end

	def destroy
		if @section.destroy
			flash[:notice] = "Section is deleted"
			redirect_to admin_sections_path, status: :see_other
	    else
			flash[:alert] = "Can't destroy, Try later"
			redirect_to admin_courses_path
		end
	end

	private
	def section_params
		params.require(:section).permit(:course_id,:teacher_id,:semester_id,:section_name)
	end
	def find_section
		@section = Section.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
    def download_file

        redirect_to root_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def contact 
  end
  def about
  end
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/admin_session_helper.rb
module AdminSessionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_registration_helper.rb
module StudentRegistrationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_registration_helper.rb
module TeacherRegistrationHelper
end

app/views/admin/sections/_form.html.erb
<%= form_for [:admin, @section], data: {turbo: false} do |f| %>
  <%= render "admin/shared/error", model: @section %>
  <div class="container-fluid w-25 border rounded shadow mt-5 p-4 text-center bg-light">
    <div class="field">
      <%= f.label :course %><br />
      <%= f.select :course_id, options_from_collection_for_select(Course.all, :id, :course_title),{}, class:"form-control"%>
    </div>

    <div class="field">
      <%= f.label :teacher %><br />
      <%= f.select :teacher_id, options_from_collection_for_select(Teacher.all, :id, :first_name),{}, class:"form-control"%>
    </div>

    <div class="field">
      <p>
        <%= f.label :semester %><br />
        <%= f.select :semester_id, options_for_select(Semester.all.map {|item| ["#{item.semester_no} - #{item.semester_type}", item.id]}),{}, class:"form-control" %>
      </p>
    </div>

    <div class="field">
      <p>
        <%= f.label :section_name %><br />
        <%= f.text_field :section_name, class:"form-control"%>
      </p>
    </div>

    <div class="actions">
      <p>
        <%= f.submit class: 'btn btn-info' %>
      </p>
    </div>

    <div class="actions">
      <%= link_to "Back", admin_sections_path, class: 'btn btn-info' %>
    </div>
  </div>
<% end %>

app/views/admin/sections/edit.html.erb
<div class="container-fluid w-25 border rounded shadow mt-5 p-4 text-center bg-light">
  <h2>Edit Section</h2>
</div>

<%= render "form" %>

app/views/admin/sections/index.html.erb
<div class="container-fluid border rounded shadow mt-5 p-4 text-center w-75 bg-light">
  <h1>Sections</h1>
</div>

<div class="container-fluid border rounded shadow mt-5 p-4 text-center w-75 bg-light">

  <table class="table bg-light ">
    <thead>
      <tr>
        <th scope="col">Sr.no</th>
        <th scope="col">Section Name</th>
        <th scope="col">Semester</th>
        <th scope="col">Course Name</th>
        <th scope="col">Teacher Name</th>
        <th scope="col">Edit | Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @sections.each do |section| %>
            <td><input type="checkbox" name="brand"> <%= section.id %> </td>
            <td><%= section.section_name%>
            <td><%= section.semester.semester_no %></td>
            <td><%= section.course.course_title %></td>
            <td><%= section.teacher.first_name %> <%= section.teacher.last_name %></td>
            <td>
              <%= link_to "Edit", edit_admin_section_path(section), class:"btn btn-info" %>
              <%= link_to "Delete", admin_section_path(section),data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              }, class:"btn btn-info" %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="container-fluid border rounded shadow mt-5 p-4 text-center w-75 bg-light">
  <p>
    <%= link_to "Add Section", new_admin_section_path, class: "btn btn-info" %>
    <%= link_to "Back", admin_dashboard_index_path, class: "btn btn-info" %>
  </p>
</div>

app/views/admin/sections/new.html.erb
<div class="container-fluid w-25 border rounded shadow mt-5 p-4 text-center bg-light">
  <h2>Add Section</h2>
</div>

<%= render "form" %>

app/views/admin/sections/show.html.erb
<p>
	<strong> ID : </strong> 
	<%= @student.id %>
</p>

<p>
	<strong> First Name : </strong> 
	<%= @student.first_name %>
</p>

<p>
	<strong> Last Name : </strong>
	<%= @student.last_name %>
</p>

<p>
	<strong> Email : </strong>
	<%= @student.email %>
</p>

<p>
	<strong> Date_of_Birth : </strong>
	<%= @student.Date_of_Birth %>
</p>


<p>
	<strong> Roll_no : </strong>
	<%= @student.roll_no %>
</p>

<p>
	<strong> Semester_Type : </strong>
	<%= @student.semesters.last.semester_type %>
</p>

<p>
	<strong> Semester : </strong>
	<%= @student.semesters.last.semester_no %>
</p>

<ul>
  <li><%= link_to "Edit", edit_admin_student_path(@student) %></li>
  <li><%= link_to "Destroy", admin_student_path(@student), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<%= link_to "Back", admin_students_path %>